### ISSUE TITLE
Failed to run on travis

### ISSUE THREAD

**Issue by raoulh** [aurelien-rainone/macdeployqtfix#8]
Hi,

I used to use your tool for generating my app bundle on travis-ci. But lately some changes did break our build with such errors from macdeployqtfix:

```
python macdeployqtfix.py build/$APP.app/Contents/MacOS/[secure] /usr/local/Cellar/qt5/5.*/

Traceback (most recent call last):

  File "macdeployqtfix.py", line 15, in <module>

    import ipdb

ImportError: No module named ipdb
```

Any idea on the cause of that?

Thanks

**Comment by arl** [comment]
Omg...this is debug code, it entered by mistake on the master branch. Sorry
for that, I'll fix it ASAP (next hours)

**Comment by arl** [comment]
Thanks for reporting

**Comment by arl** [comment]
I just pushed a fix, I'll let you close the issue when and if it's fixed on your side.

**Comment by raoulh** [comment]
Works now! Awesome!

Thanks a lot for being so fast!

**Comment by arl** [comment]
Great!
I guess the guilty commit entered in the master at least one week ago...

That shouldn't happen again thanks to your report and to PR #9
Have a nice day


On 31 Oct 2017 10:06, "raoulh" <notifications@github.com> wrote:

Works now! Awesome!

Thanks a lot for being so fast!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/aurelien-rainone/macdeployqtfix/issues/8#issuecomment-340701251>,
or mute the thread
